version: "3.2"
services:
  mysql:
    container_name: dotnet_pomelo_ms_json_mysql
    image: mysql:8.0
    volumes:
      - ./data/mysql:/var/lib/mysql:rw,delegated
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      TZ: "America/Sao_Paulo"
    ports:
      - "33062:3306"
